name: Trigger auto deployment for backend-pis

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop-diego ]
    paths:
    - '**'
    - '.github/workflows/backend-pis-AutoDeployTrigger-3d8403ce-20e0-44a7-8586-9445e27d6096.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BACKENDPIS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BACKENDPIS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BACKENDPIS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.BACKENDPIS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BACKENDPIS_REGISTRY_PASSWORD }}
          containerAppName: backend-pis
          resourceGroup: DefaultResourceGroup-CUS
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


